# Generated by Django 6.0 on 2025-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=50)),
                ('estimated_revenue', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
