# Generated by Django 5.0.6 on 2026-01-02 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(default='General Info')),
                ('source_domain', models.CharField(max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('found_cin', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='agents.company')),
            ],
        ),
    ]
