"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.x/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.x/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'agents',
    'corsheaders',
    'mozilla_django_oidc',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # All API endpoints require a valid OIDC-issued session by default.
    # Unauthenticated requests receive HTTP 401.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Refreshes the OIDC token on each request and redirects browser clients
    # to the identity provider when the session has expired.
    'mozilla_django_oidc.middleware.SessionRefresh',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration — driven entirely by the DATABASE_URL environment variable.
# For local development set DATABASE_URL=sqlite:///db.sqlite3 in your .env file.
# For production use a full connection string, e.g.:
#   postgresql://user:password@host:5432/dbname
_DATABASE_URL = os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}')

import urllib.parse as _urlparse  # stdlib — no extra dependency needed

_db_url = _urlparse.urlparse(_DATABASE_URL)
_db_scheme = _db_url.scheme.split('+')[0]  # handle e.g. "postgresql+psycopg2"

_ENGINE_MAP = {
    'sqlite': 'django.db.backends.sqlite3',
    'postgresql': 'django.db.backends.postgresql',
    'postgres': 'django.db.backends.postgresql',
    'mysql': 'django.db.backends.mysql',
    'oracle': 'django.db.backends.oracle',
}

_db_engine = _ENGINE_MAP.get(_db_scheme, 'django.db.backends.sqlite3')
_db_name = _db_url.path.lstrip('/') if _db_scheme != 'sqlite' else _db_url.path.lstrip('/')

# For SQLite, resolve relative paths against BASE_DIR
if _db_scheme == 'sqlite' and not _db_url.path.startswith('/'):
    _db_name = str(BASE_DIR / _db_name)

DATABASES = {
    'default': {
        'ENGINE': _db_engine,
        'NAME': _db_name,
        'USER': _db_url.username or '',
        'PASSWORD': _db_url.password or '',
        'HOST': _db_url.hostname or '',
        'PORT': str(_db_url.port) if _db_url.port else '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Allow React to talk to Django

# 🟢 ALLOW ALL: Grants access to ANY frontend (Localhost, EC2, Vercel, etc.)
CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]


# ---------------------------------------------------------------------------
# OIDC / OAuth2 — Authentication via Identity Provider
# ---------------------------------------------------------------------------
# Set the following environment variables before running the application:
#
#   OIDC_RP_CLIENT_ID            – OAuth2 client ID issued by the IdP
#   OIDC_RP_CLIENT_SECRET        – OAuth2 client secret issued by the IdP
#   OIDC_OP_AUTHORIZATION_ENDPOINT – IdP's /authorize URL
#   OIDC_OP_TOKEN_ENDPOINT         – IdP's /token URL
#   OIDC_OP_USER_ENDPOINT          – IdP's /userinfo URL
#   OIDC_OP_JWKS_ENDPOINT          – IdP's JWKS (public key) URL
#   OIDC_RP_SIGN_ALGO              – JWT signing algorithm (default RS256)
#
# Example for Microsoft Entra ID (Azure AD):
#   OIDC_OP_AUTHORIZATION_ENDPOINT=https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize
#   OIDC_OP_TOKEN_ENDPOINT=https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token
#   OIDC_OP_USER_ENDPOINT=https://graph.microsoft.com/oidc/userinfo
#   OIDC_OP_JWKS_ENDPOINT=https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys

OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', '')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET', '')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT', '')
OIDC_OP_TOKEN_ENDPOINT = os.environ.get('OIDC_OP_TOKEN_ENDPOINT', '')
OIDC_OP_USER_ENDPOINT = os.environ.get('OIDC_OP_USER_ENDPOINT', '')
OIDC_OP_JWKS_ENDPOINT = os.environ.get('OIDC_OP_JWKS_ENDPOINT', '')
OIDC_RP_SIGN_ALGO = os.environ.get('OIDC_RP_SIGN_ALGO', 'RS256')

# Where to send users after login / logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Use the OIDC backend first, fall back to Django's built-in backend
# (the built-in backend is kept so the /admin interface continues to work)
AUTHENTICATION_BACKENDS = [
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ---------------------------------------------------------------------------
# Session cookie security
# Session data is kept server-side (Django's DB-backed session store).
# The cookie itself is HttpOnly so JavaScript cannot access it.
# ---------------------------------------------------------------------------
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True          # Prevents JS access — always True
SESSION_COOKIE_SECURE = not DEBUG       # Transmit over HTTPS only in production
SESSION_COOKIE_SAMESITE = 'Lax'        # CSRF mitigation for same-site requests